apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
  #the name of the secret that will created in k8s
    name: secret-from-aws 
    creationPolicy: Owner
  dataFrom:
  - extract:
  # the name of the secret in secret manger in aws
      key: SECRET 