apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
          #the name of the secret for the credetials for the user
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
          #the name of the secret for the credetials for the user
            name: awssm-secret 
            key: secret-access-key